package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 13:32:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testToString32 */
  @Test
  public void testToString32() {    // Jasen: 32
    Jasen jasen = new Jasen(); 
    jasen.parse("   3  |  Ankka Aku   | Akkuli  |  Ankkatie |  30003  |  ANKKALINNA"); 
    assertEquals("From: Jasen line: 35", true, jasen.toString().startsWith("3|Ankka Aku|Akkuli|Ankkatie|30003|ANKKALINNA")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi53 */
  @Test
  public void testGetNimi53() {    // Jasen: 53
    Jasen aku = new Jasen(); 
    aku.vastaaAkuAnkka(); 
    assertEquals("From: Jasen line: 56", "Aku Ankka", aku.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi105 */
  @Test
  public void testRekisteroi105() {    // Jasen: 105
    Jasen aku1 = new Jasen(); 
    assertEquals("From: Jasen line: 107", 1, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Jasen aku2 = new Jasen(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Jasen line: 113", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse157 */
  @Test
  public void testParse157() {    // Jasen: 157
    Jasen jasen = new Jasen(); 
    jasen.parse("    3   |   Aku Ankka   |   Akkuli"); 
    assertEquals("From: Jasen line: 160", 3, jasen.getTunnusNro()); 
    assertEquals("From: Jasen line: 161", false, jasen.toString().startsWith("3|Aku Ankka| Akkuli|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone281 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone281() throws CloneNotSupportedException {    // Jasen: 281
    Jasen jasen = new Jasen(); 
    jasen.parse("   3  |  Ankka Aku   | Akkuli | Ankkatie | 30003 | ANKKALINNA"); 
    Jasen kopio = jasen.clone(); 
    assertEquals("From: Jasen line: 286", jasen.toString(), kopio.toString()); 
    jasen.parse("   4  |  Ankka Tupu   | Ankkatie | 30003 | ANKKALINNA"); 
    assertEquals("From: Jasen line: 288", false, kopio.toString().equals(jasen.toString())); 
  } // Generated by ComTest END
}