package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 13:08:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Jasenet: 32
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(); 
    assertEquals("From: Jasenet line: 36", 0, jasenet.getLkm()); 
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 37", 1, jasenet.getLkm()); 
    jasenet.lisaa(aku2); assertEquals("From: Jasenet line: 38", 2, jasenet.getLkm()); 
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 39", 3, jasenet.getLkm()); 
    assertEquals("From: Jasenet line: 40", aku1, jasenet.anna(0)); 
    assertEquals("From: Jasenet line: 41", aku2, jasenet.anna(1)); 
    assertEquals("From: Jasenet line: 42", aku1, jasenet.anna(2)); 
    assertEquals("From: Jasenet line: 43", false, jasenet.anna(1) == aku1); 
    assertEquals("From: Jasenet line: 44", true, jasenet.anna(1) == aku2); 
    try {
    assertEquals("From: Jasenet line: 45", aku1, jasenet.anna(3)); 
    fail("Jasenet: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 46", 4, jasenet.getLkm()); 
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 47", 5, jasenet.getLkm()); 
  } // Generated by ComTest END
}