package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 13:08:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KerhoTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaaJasen35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaaJasen35() throws SailoException {    // Kerho: 35
    Kerho kerho = new Kerho(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); 
    assertEquals("From: Kerho line: 40", 0, kerho.getJasenia()); 
    kerho.lisaaJasen(aku1); assertEquals("From: Kerho line: 41", 1, kerho.getJasenia()); 
    kerho.lisaaJasen(aku2); assertEquals("From: Kerho line: 42", 2, kerho.getJasenia()); 
    kerho.lisaaJasen(aku1); assertEquals("From: Kerho line: 43", 3, kerho.getJasenia()); 
    assertEquals("From: Kerho line: 44", 3, kerho.getJasenia()); 
    assertEquals("From: Kerho line: 45", aku1, kerho.annaJasen(0)); 
    assertEquals("From: Kerho line: 46", aku2, kerho.annaJasen(1)); 
    assertEquals("From: Kerho line: 47", aku1, kerho.annaJasen(2)); 
    try {
    assertEquals("From: Kerho line: 48", aku1, kerho.annaJasen(3)); 
    fail("Kerho: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kerho.lisaaJasen(aku1); assertEquals("From: Kerho line: 49", 4, kerho.getJasenia()); 
    kerho.lisaaJasen(aku1); assertEquals("From: Kerho line: 50", 5, kerho.getJasenia()); 
  } // Generated by ComTest END
}