package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 14:02:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsallistuminenTest {


  // Generated by ComTest BEGIN
  /** testToString48 */
  @Test
  public void testToString48() {    // Osallistuminen: 48
    Osallistuminen osallistuminen = new Osallistuminen(); 
    osallistuminen.parse("   1  |  1  | 1 "); 
    assertEquals("From: Osallistuminen line: 51", true, osallistuminen.toString().startsWith("1|1|1")); 
  } // Generated by ComTest END
}