package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 13:15:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReissuTest {



  // Generated by ComTest BEGIN
  /** testParse55 */
  @Test
  public void testParse55() {    // Reissu: 55
    Reissu reissu = new Reissu(); 
    reissu.parse("1|Testi reissu|01.01.2025|Määränpää|-"); 
    assertEquals("From: Reissu line: 58", 1, reissu.getReissuId()); 
    assertEquals("From: Reissu line: 59", "Testi reissu", reissu.getReissuNimi());
  } // Generated by ComTest END
}