package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 15:49:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TehtavaTest {



  // Generated by ComTest BEGIN
  /** testToString51 */
  @Test
  public void testToString51() {    // Tehtava: 51
    Tehtava tehtava = new Tehtava(); 
    tehtava.parse("   1  |  Testi tehtävä   | 1|  1"); 
    assertEquals("From: Tehtava line: 54", true, tehtava.toString().startsWith("1|Testi tehtävä|1|1")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse173 */
  @Test
  public void testParse173() {    // Tehtava: 173
    Tehtava tehtava = new Tehtava(); 
    tehtava.parse("    3   |   Keitä puuro   |   1  | 2 "); 
    assertEquals("From: Tehtava line: 176", 3, tehtava.getTehtavaNro()); 
    assertEquals("From: Tehtava line: 177", false, tehtava.toString().startsWith("3|Keitä puuro| 1|2")); 
  } // Generated by ComTest END
}