package fxkelmienkerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxkelmienkerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.05.11 15:44:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TehtavatTest {


  // Generated by ComTest BEGIN
  /** testLisaa54 */
  @Test
  public void testLisaa54() {    // Tehtavat: 54
    Tehtavat tehtavat = new Tehtavat(); 
    Tehtava t1 = new Tehtava(), t2 = new Tehtava(); 
    assertEquals("From: Tehtavat line: 57", 0, tehtavat.getLkm()); 
    tehtavat.lisaa(t1); assertEquals("From: Tehtavat line: 58", 1, tehtavat.getLkm()); 
    tehtavat.lisaa(t2); assertEquals("From: Tehtavat line: 59", 2, tehtavat.getLkm()); 
    tehtavat.lisaa(t1); assertEquals("From: Tehtavat line: 60", 3, tehtavat.getLkm()); 
    tehtavat.lisaa(t1); assertEquals("From: Tehtavat line: 61", 4, tehtavat.getLkm()); 
    tehtavat.lisaa(t1); assertEquals("From: Tehtavat line: 62", 5, tehtavat.getLkm()); 
  } // Generated by ComTest END
}